### ISSUE TITLE
Code integrity issues

### ISSUE THREAD

**Issue by ShuaiLyu0110** [hwy9855/GSR#1]
Can you share the complete code and deployment process?

**Comment by hwy9855** [comment]
Thanks for your interest on our work. We are currently processing the complete code base with instruction and model checkpoints, plan to finish all within this month.

**Comment by 6-git** [comment]
I am also looking forward to the release of all the code and data. Very grateful for your selfless dedication.

**Comment by hwy9855** [comment]
The complete instruction and model checkpoints are updated now.
